development:
  perform_authentication: false
  #cis_fetch_data: "http://192.168.0.8/onpoint.in/cis_awb_data.php"
  cis_fetch_data: "http://122.160.165.182:1079/onpoint.in/cis_awb_data.php"
  cis_fetch_clients: "http://192.168.0.8/onpoint.in/cis_client_data.php"
  master_password_email: "hitesh@onpoint.in"

test:
  perform_authentication: false

production:
  perform_authentication: true
  username: admin
  password: secret
  cis_fetch_data: "http://122.160.165.182:1079/onpoint.in/cis_awb_data.php"
  cis_fetch_clients: "http://122.160.165.182:1079/onpoint.in/cis_client_data.php"
  master_password_email: "hitesh@onpoint.in"

general:
  manager_default_limit: "10"
  manager_pagination_options: [10,20,50,100]
  status_id:
    1: "Active"
    2: "Inactive"
  status:
    Active: 1
    Inactive: 2
  margin_type_id:
    1: "Percent"
    2: "Amount"
  margin_type:
    Percent: 1
    Amount: 2
  packet_type_id:
    1: "Sample"
    2: "Commercial"
  packet_type:
    Sample: 1
    Commercial: 2
  des_type_id:
    1: "International"
    2: "Domestic"
  des_type:
    Intl: 1
    Dom: 2
  rate_type_id:
    1: "Basic"
    2: "Perkg"
  rate_type:
    Basic: 1
    Perkg: 2
  state_id:
    1: "Enabled"
    0: "Disabled"
  state:
    Enabled: 1
    Disabled: 0
  quote_option_id:
    5: "Options"
    10: "Text Field"
  quote_option:
    Options: 5
    Text_Field: 10
  rate_quote_status_id:
    5: "Draft"
    10: "Sent"
  rate_master_category_id:
    6: "Express"
    9: "Standard"
    3: "Economic"
  rate_master_category:
    Express: 6
    Standard: 9
    Economic: 3
  admin_type_id:
    1: "Admin"
    8: "Staff"
  admin_type:
    Admin: 1
    Staff: 8
  rate_quote_status:
    Draft: 5
    Sent: 10
  delivery_days:
    1-0: "1 Bizz Day"
    2-0: "2 Bizz Days"
    3-0: "3 Bizz Days"
    4-0: "4 Bizz Days"
    5-0: "5 Bizz Days"
    6-0: "6 Bizz Days"
    7-0: "7 Bizz Days"
    8-0: "8 Bizz Days"
    9-0: "9 Bizz Days"
    10-0: "10 Bizz Days"
    1-1: "1-2 Bizz Days"
    2-1: "2-3 Bizz Days"
    3-1: "3-4 Bizz Days"
    4-1: "4-5 Bizz Days"
    5-1: "5-6 Bizz Days"
    1-2: "1-3 Bizz Days"
    2-2: "2-4 Bizz Days"
    3-2: "3-5 Bizz Days"
    4-2: "4-6 Bizz Days"
    5-2: "5-7 Bizz Days"
    6-2: "6-8 Bizz Days"
    7-2: "7-9 Bizz Days"
    8-2: "8-10 Bizz Days"
  service_tax: "14.5"
  data_fetch_interval:
    1: "Daily"
    7: "Weekly"
    15: "Fortnightly"
    30: "Monthly"
  admin_permission_set:
    zones: "Zones"
    destination_country_list: "Destinations - Country List"
    destination_city_list: "Destinations - City List"
    networks: "Networks"
    manage_rates_rate_master: "Manage Rates - Rate Master"
    manage_rates_feed_rates: "Manage Rates - Feed Rates"
    rate_search: "Rate Search"
    rate_query_log: "Rate Query Log"
    rate_quotes: "Rate Quotes"
    rate_quote_options: "Rate Quote Options"
    users: "Users"
    clients: "Clients"
    documents: "Documents"
  document_available_to_id:
    1: "All Destinations"
    2: "All International"
    3: "All Domestic"
    4: "Let me choose"
  document_available_to:
    all_destinations: "1"
    all_international: "2"
    all_domestic: "3"
    let_me_choose: "4"
  default_margin_1: "25"
  default_margin_2: "20"